# Generated by Django 5.0.6 on 2026-05-12 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('starting_odo', models.IntegerField(blank=True, null=True)),
                ('ending_odo', models.IntegerField(blank=True, null=True)),
                ('total_miles', models.FloatField(default=0.0)),
                ('remarks', models.TextField(blank=True, default='')),
                ('hours_off', models.FloatField(default=0.0)),
                ('hours_sleeper', models.FloatField(default=0.0)),
                ('hours_driving', models.FloatField(default=0.0)),
                ('hours_onduty', models.FloatField(default=0.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['log_date'],
                'unique_together': {('trip', 'log_date')},
            },
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('status', models.CharField(choices=[('off', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('onduty', 'On Duty (Not Driving)')], max_length=10)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('stop_kind', models.CharField(blank=True, default='', max_length=16)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='logs.dailylog')),
            ],
            options={
                'ordering': ['start_minute'],
            },
        ),
    ]
