# Generated by Django 5.0.6 on 2026-05-12 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_name', models.CharField(blank=True, default='', max_length=120)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=120)),
                ('truck_number', models.CharField(blank=True, default='', max_length=40)),
                ('current_location', models.JSONField()),
                ('pickup_location', models.JSONField()),
                ('dropoff_location', models.JSONField()),
                ('cycle_used_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('depart_at', models.DateTimeField()),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('route_geojson', models.JSONField(blank=True, null=True)),
                ('total_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('total_drive_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('plan_version', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('kind', models.CharField(choices=[('start', 'Start'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('break_30', '30-min Break'), ('rest_10', '10-hr Reset'), ('restart_34', '34-hr Restart')], max_length=16)),
                ('label', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('mile_marker', models.FloatField()),
                ('arrive_at', models.DateTimeField()),
                ('depart_at', models.DateTimeField()),
                ('duration_min', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('trip', 'sequence')},
            },
        ),
    ]
